const menuContent = [
  {
    id: 1,
    name: '基础数据',
    type: 1,
    source: null,
    selector: 'menu-base-data',
    uri: null,
    parentid: 0,
    remark: '',
    status: 1,
    hidden: false,
    style: 'click',
    children: [
      // {
      //   id: 10,
      //   name: "添加影像数据",
      //   type: 2,
      //   source: null,
      //   selector: "menu-base-data_add_images",
      //   uri: null,
      //   parentid: 1,
      //   remark: "",
      //   status: 1,
      //   hidden: false,
      //   style: "click"
      // },
      // {
      //   id: 11,
      //   name: "添加矢量文件",
      //   type: 2,
      //   source: null,
      //   selector: "menu-base-data_add_vector_file",
      //   uri: null,
      //   parentid: 1,
      //   remark: "",
      //   status: 1,
      //   hidden: false,
      //   style: "click"
      // },
      // {
      //   id: 12,
      //   name: "显示在线影像",
      //   type: 2,
      //   source: null,
      //   selector: "menu-base-data_show_online_image",
      //   uri: null,
      //   parentid: 1,
      //   remark: "",
      //   status: 1,
      //   hidden: false,
      //   style: "select"
      // },
      {
        id: 13,
        name: "显示保护地影像",
        type: 2,
        source: null,
        selector: "menu-base-data_show_protect_image",
        uri: null,
        parentid: 1,
        remark: "",
        status: 1,
        hidden: false,
        style: "select"
      },
      {
        id: 14,
        name: "显示基础信息",
        type: 2,
        source: null,
        selector: "menu-base-data_show_base_info",
        uri: null,
        parentid: 1,
        remark: "",
        status: 1,
        hidden: false,
        style: "select"
      },
      {
        id: 15,
        name: "显示保护地信息",
        type: 2,
        source: null,
        selector: "menu-base-data_show_protect_info",
        uri: null,
        parentid: 1,
        remark: "",
        status: 1,
        hidden: false,
        style: "select"
      },
      {
        id: 16,
        name: "显示小班数据",
        type: 2,
        source: null,
        selector: "menu-base-data_show_small_data",
        uri: null,
        parentid: 1,
        remark: "",
        status: 1,
        hidden: false,
        style: "select"
      },
      {
        id: 17,
        name: "显示人类活动",
        type: 2,
        source: null,
        selector: "menu-base-data_show_human_action",
        uri: null,
        parentid: 1,
        remark: "",
        status: 1,
        hidden: false,
        style: "select"
      },
      {
        id: 18,
        name: "显示人类活动变化",
        type: 2,
        source: null,
        selector: "menu-base-data_show_humanAct_change",
        uri: null,
        parentid: 1,
        remark: "",
        status: 1,
        hidden: false,
        style: "select"
      },
      {
        id: 19,
        name: "显示实地核查数据",
        type: 2,
        source: null,
        selector: "menu-base-data_show_fieldAudit",
        uri: null,
        parentid: 1,
        remark: "",
        status: 1,
        hidden: false,
        style: "select"
      },
      {
        id: 20,
        name: "显示自主巡查数据",
        type: 2,
        source: null,
        selector: "menu-base-data_independent_inspection",
        uri: null,
        parentid: 1,
        remark: "",
        status: 1,
        hidden: false,
        style: "select"
      },
      {
        id: 36,
        name: "显示绘制图斑",
        type: 2,
        source: null,
        selector: "menu-base-data_show-draw-layer",
        uri: null,
        parentid: 1,
        remark: "",
        status: 1,
        hidden: false,
        style: "select"
      }
    ]
  },
  {
    id: 2,
    name: '遥感监测',
    type: 1,
    source: null,
    selector: 'menu-remote-monitor',
    uri: null,
    parentid: 0,
    remark: '',
    status: 1,
    hidden: false,
    style: 'click',
    children: [
      {
        id: 21,
        name: "人类活动变化",
        type: 2,
        source: null,
        selector: "menu-remote-monitor_humanAct-change",
        uri: null,
        parentid: 2,
        remark: "",
        status: 1,
        hidden: false,
        style: "click"
      },
      {
        id: 22,
        name: "影像对比",
        type: 2,
        source: null,
        selector: "menu-remote-monitor_image-contrast",
        uri: null,
        parentid: 2,
        remark: "",
        status: 1,
        hidden: false,
        style: "click"
      }
    ]
  },
  {
    id: 3,
    name: '遥感验证',
    type: 1,
    source: null,
    selector: 'menu-remote-sensing-verification',
    uri: null,
    parentid: 0,
    remark: '',
    status: 1,
    hidden: false,
    style: 'click',
    // children:[
    // {
    //   id: 23,
    //   name: "单点坐标",
    //   type: 2,
    //   source: null,
    //   selector: "menu-remote-sensing-verification_coordinate",
    //   uri: null,
    //   parentid: 3,
    //   remark: "",
    //   status: 1,
    //   hidden: false,
    //   style: "click"
    // },
    // {
    //   id: 24,
    //   name: "表格导入",
    //   type: 2,
    //   source: null,
    //   selector: "menu-remote-sensing_table-import",
    //   uri: null,
    //   parentid: 3,
    //   remark: "",
    //   status: 1,
    //   hidden: false,
    //   style: "click"
    // },
    // {
    //   id: 25,
    //   name: "矢量导入",
    //   type: 2,
    //   source: null,
    //   selector: "menu-remote-sensing-vector-import",
    //   uri: null,
    //   parentid: 3,
    //   remark: "",
    //   status: 1,
    //   hidden: false,
    //   style: "click"
    // },
    // {
    //   id: 26,
    //   name: "系统数据对比",
    //   type: 2,
    //   source: null,
    //   selector: "menu-remote-sensing_data-contrast",
    //   uri: null,
    //   parentid: 3,
    //   remark: "",
    //   status: 1,
    //   hidden: false,
    //   style: "click"
    // }
    // ]
  },
  {
    id: 4,
    name: '实地核查',
    type: 1,
    source: null,
    selector: 'menu-field-audit',
    uri: null,
    parentid: 0,
    remark: '',
    status: 1,
    hidden: false,
    style: 'click',
    children: [
      {
        id: 27,
        name: "创建任务",
        type: 2,
        source: null,
        selector: "menu-field-audit_create-task",
        uri: null,
        parentid: 4,
        remark: "",
        status: 1,
        hidden: false,
        style: "click"
      }, {
        id: 28,
        name: "任务查询",
        type: 2,
        source: null,
        selector: "menu-field-audit_task-query",
        uri: null,
        parentid: 4,
        remark: "",
        status: 1,
        hidden: false,
        style: "click"
      }, {
        id: 29,
        name: "设备监控",
        type: 2,
        source: null,
        selector: "menu-field-audit_device-monitor",
        uri: null,
        parentid: 4,
        remark: "",
        status: 1,
        hidden: false,
        style: "click"
      }, {
        id: 30,
        name: "核查管理",
        type: 2,
        source: null,
        selector: "menu-field-audit_verification-management",
        uri: null,
        parentid: 4,
        remark: "",
        status: 1,
        hidden: false,
        style: "click"
      },
      // {
      //   id: 31,
      //   name: "数据上传",
      //   type: 2,
      //   source: null,
      //   selector: "menu-field-audit_data-upload",
      //   uri: null,
      //   parentid: 4,
      //   remark: "",
      //   status: 1,
      //   hidden: false,
      //   style: "click"
      // }
    ]
  },
  {
    id: 5,
    name: '处置意见',
    type: 1,
    source: null,
    selector: 'menu-dispose-opinion',
    uri: null,
    parentid: 0,
    remark: '',
    status: 1,
    hidden: false,
    style: 'click'
  },
  {
    id: 6,
    name: '统计分析',
    type: 1,
    source: null,
    selector: 'menu-statistical-analysis',
    uri: null,
    parentid: 0,
    remark: '',
    status: 1,
    hidden: false,
    style: 'click',
  },
  {
    id: 7,
    name: '报告管理',
    type: 1,
    source: null,
    selector: 'menu-report',
    uri: null,
    parentid: 0,
    remark: '',
    status: 1,
    hidden: false,
    style: 'click',
    children: [
      {
        id: 32,
        name: "报告生成",
        type: 2,
        source: null,
        selector: "menu-report_build",
        uri: null,
        parentid: 7,
        remark: "",
        status: 1,
        hidden: false,
        style: "click"
      },
      // {
      //   id: 33,
      //   name: "报告上传",
      //   type: 2,
      //   source: null,
      //   selector: "menu-report_upload",
      //   uri: null,
      //   parentid: 7,
      //   remark: "",
      //   status: 1,
      //   hidden: false,
      //   style: "click"
      // }, {
      {
        id: 34,
        name: "报告列表",
        type: 2,
        source: null,
        selector: "menu-report_list",
        uri: null,
        parentid: 7,
        remark: "",
        status: 1,
        hidden: false,
        style: "click"
      },
      // {
      //   id: 35,
      //   name: "报表图像的关联和上传",
      //   type: 2,
      //   source: null,
      //   selector: "menu-report_image_upload",
      //   uri: null,
      //   parentid: 7,
      //   remark: "",
      //   status: 1,
      //   hidden: false,
      //   style: "click"
      // }
    ]
  },
  {
    id: 8,
    name: '自主巡查',
    type: 1,
    source: null,
    selector: 'menu-independent-inspection',
    uri: null,
    parentid: 0,
    remark: '',
    status: 1,
    hidden: false,
    style: 'click'
  }
  // ,
  // {
  //   id: 9,
  //   name: '系统管理',
  //   type: 1,
  //   source: null,
  //   selector: 'menu-system-admin',
  //   uri: null,
  //   parentid: 0,
  //   remark: '',
  //   status: 1,
  //   hidden: false,
  //   style: 'click',
  // }
];

export {
  menuContent
}
